name: 'Branch Restriction Check'
on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          if [[ "$GITHUB_HEAD_REF" != "development" ]]; then
            echo "Only PRs from development branch are allowed to merge into main."
            exit 1
          fi
